name: kotc_core
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  dio:
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

